services:
  postgres:
    image: postgres:16 
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - /Volumes/Data/docker/postgres/data:/var/lib/postgresql/data
    networks:
      - shared_network
volumes:
  postgres_data:

networks:
  shared_network:
    external: true
